app.addModel 'status', '/v1/status'
app.addModel 'session', '/v1/session/new'
app.addModel 'apps', '/v1/apps'
app.addModel 'recipes', '/v1/recipes/:app/:env'
app.addModel 'cap', '/v1/cap/:app/:env'
app.addModel 'logs', '/v1/logs/:app/:env'
app.addModel 'envs', '/v1/apps/:app/envs/:env'
